@echo off
setlocal
cd /d "%~dp0"

set BBY_GRAPHQL_REGISTRY_DIR=%~dp0mapping_run
set BBY_DT_CORE_ONLY=0
set BBY_DT_SKIP_REVIEWS=0
set BBY_DT_GRAPHQL_REPLAY=1
set BBY_DT_PDP_GRAPHQL_DISCOVERY=1
set BBY_DT_PDP_GRAPHQL_DISCOVERY_SECONDS=8
set BBY_GRAPHQL_REVIEW_PAGE_SIZE=20
set BBY_DT_SKIP_SIMILAR=1
set BBY_DT_REVIEW_DOM_FALLBACK=0
set BBY_DT_REACTIVE_REFRESH_ON_GRAPHQL_ERROR=1
set BBY_DT_REACTIVE_COOLDOWN_MIN=300
set BBY_DT_REACTIVE_COOLDOWN_MAX=600
set BBY_DT_RESTART_EVERY=6
set BBY_DT_COOLDOWN_EVERY=6
set BBY_DT_COOLDOWN_MIN=240
set BBY_DT_COOLDOWN_MAX=480
set BBY_RATE_MIN_DELAY=16
set BBY_RATE_MAX_DELAY=34
set BBY_RATE_MAX_PER_MINUTE=3
set BBY_RATE_MAX_PER_HOUR=90

python bby_tv_dt1.py %*
